spring.application.name=loja-baozi
spring.datasource.url=jdbc:mysql://localhost:3306/loja_baozi
spring.datasource.username=baozi
spring.datasource.password=baozi123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true